### ISSUE TITLE
Gatekeeper returning formatting error (eg: 'utf-8' codec can't decode byte 0x86 in position 23: invalid start byte)

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/gatekeeper#5]
Some files/directories cannot be traversed and printed due to formatting errors. Either force formatting on output, skip those that cannot be displayed, or restrict further the list of items that can be searched by excluding those that are not compatible.

Only check text files? This may be due to certain types of binary files such as DB files or images?

```
Traceback (most recent call last):
  File "/usr/local/bin/gatekeeper-scout", line 33, in <module>
    sys.exit(load_entry_point('gatekeeper-suite', 'console_scripts', 'gatekeeper-scout')())
  File "/Users/jhammond/git/personal/gatekeeper/gatekeeper/scout.py", line 40, in main
    for line_number, line in enumerate(single_file, 1):
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 23: invalid start byte
```

**Comment by Justintime50** [comment]
Commit 0922c4b11d05ca9f9d48e338557991caed50a300 closes this.
